csf_enabled_check() {}
csf_running_check() {}
TESTING_mode_check() {}
RESTRICT_SYSLOG_option_check() {}
AUTO_UPDATES_option_check() {}
lfd_enabled_check() {}
Incoming_MySQL_port_check() {}
SMTP_BLOCK_option_check() {}
LF_SCRIPT_ALERT_option_check() {}
LF_SSHD_option_check() {}
LF_FTPD_option_check() {}
LF_SMTPAUTH_option_check() {}
LF_POP3D_option_check() {}
LF_IMAPD_option_check() {}
LF_HTACCESS_option_check() {}
LF_MODSEC_option_check() {}
LF_CPANEL_option_check() {}
LF_CPANEL_ALERT_option_check() {}
SYSLOG_CHECK_option_check() {}
RESTRICT_UI_option_check() {}
LF_DIRWATCH_option_check() {}
LF_INTEGRITY_option_check() {}
FASTSTART_option_check() {}
URLGET_option_check() {}
PT_USERKILL_option_check() {}
PT_SKIP_HTTP_option_check() {}
LF_IPSET_option_check() {}
PT_ALL_USERS_option_check() {}
LF_SMTPAUTH_sanity_check() {}
