Check_cPanel_login_is_SSL_only() {}
Check_boxtrapper_is_disabled() {}
Check_GreyListing_is_disabled() {}
Check_popbeforesmtp_is_disabled() {}
Check_max_emails_per_hour_is_set() {}
Check_Reset_Password_for_cPanel_accounts() {}
Check_Reset_Password_for_Subaccounts() {}
Check_cPanelID_for_cpaneld() {}
Check_cPanelID_for_webmaild() {}
Check_cPanelID_for_whostmgrd() {}
Check_compilers() {}
Check_Anonymous_FTP_Logins() {}
Check_Anonymous_FTP_Uploads() {}
Check_pure-ftpd_weak_SSL-TLS_Ciphers() {}
Check_FTP_Logins_with_Root_Password() {}
Check_allow_remote_domains() {}
Check_block_common_domains() {}
Check_allow_park_domains() {}
Check_proxy_subdomains() {}
Check_cPAddons_update_email_to_owner() {}
Check_cPAddons_update_email_to_root() {}
Check_cPanel_tree() {}
Check_cPanel_updates() {}
Check_package_updates() {}
Check_security_updates() {}
Check_accounts_that_can_access_a_cPanel_user() {}
Check_cPanel_php_for_register_globals() {}
Check_cPanel_php.ini_file_for_register_globals() {}
Check_cPanel_passwords_in_email() {}
Check_core_dumps() {}
Check_Cookie_IP_Validation() {}
Check_MD5_passwords_with_Apache() {}
Check_Referrer_Blank_Security() {}
Check_Referrer_Security() {}
Check_HTTP_Authentication() {}
Check_Parent_Security() {}
Check_Domain_Lookup_Security() {}
Check_Password_ENV_variable() {}
Check_SMTP_Restrictions() {}
Check_nameservers() {}
Check_AppConfig_Required() {}
Check_AppConfig_as_root() {}
Check_AppConfig_ACLs() {}
Check_AppConfig_Feature_List() {}
Check_Security_Tokens() {}
